In [6]:
import numpy as np

In [94]:
# N = 4, D = 1

# Inputs:
# x1 = 2
# x2 = 4
# x3 = 6
# x4 = 8

# To respect interleaving condition we further set:
# b1 = 1
# b2 = 3
# b3 = 5
# b4 = 7

# A.w = y


In [95]:
# Random input, sorted to respect interleaving condition
X = np.sort(np.array([2, 4, 6, 8]))
X

array([2, 4, 6, 8])

In [96]:
# Random b that respects interleaving condition
b = X-1
b

array([1, 3, 5, 7])

In [97]:
# Function to replicate
def myfunc(x):
    return np.cos(x)**3+np.tanh(x)

In [98]:
y = myfunc(X)
y

array([ 0.89196002,  0.72006007,  1.8851946 ,  0.9969195 ])

In [99]:
A = np.transpose(np.ones((len(X), len(X)))*X) + np.ones((len(X), len(X)))*-b
A[A<0] = 0
A

array([[ 1.,  0.,  0.,  0.],
       [ 3.,  1.,  0.,  0.],
       [ 5.,  3.,  1.,  0.],
       [ 7.,  5.,  3.,  1.]])

In [100]:
# Weights matrix
w = np.linalg.solve(A, y) 
w

array([ 0.89196002, -1.95582   ,  3.29285448, -5.34626411])

In [101]:
np.allclose(np.dot(A, w), y)

True

In [102]:
# E.g, y1
w[0]*(X[0]-b[0]), y[0]

(0.89196002432805155, 0.89196002432805166)

In [103]:
# E.g, y2
(w[0]*(X[1]-b[0]))+(w[1]*(X[1]-b[1])), y[1]

(0.72006007377448045, 0.72006007377448111)

In [106]:
# So for n=4 and d=1 we have learnt
len(w) + len(b)
# Should be 2n+d = 9?
# Where is 9th

8